<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomerStaffsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customer_staffs')->delete();
        
        \DB::table('customer_staffs')->insert(array (
            0 => 
            array (
                'id' => 488,
                'user_id' => 766,
                'customer_id' => 20721,
                'realname' => 'Budi Sihombing',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            1 => 
            array (
                'id' => 489,
                'user_id' => 767,
                'customer_id' => 20722,
                'realname' => 'Umi Wibowo',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            2 => 
            array (
                'id' => 490,
                'user_id' => 768,
                'customer_id' => 20723,
                'realname' => 'Eko Hutapea',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            3 => 
            array (
                'id' => 491,
                'user_id' => 769,
                'customer_id' => 20724,
                'realname' => 'Tono Tambunan',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            4 => 
            array (
                'id' => 492,
                'user_id' => 770,
                'customer_id' => 20725,
                'realname' => 'Agus Sihombing',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            5 => 
            array (
                'id' => 493,
                'user_id' => 771,
                'customer_id' => 20726,
                'realname' => 'Gita Sinaga',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            6 => 
            array (
                'id' => 494,
                'user_id' => 772,
                'customer_id' => 20727,
                'realname' => 'Gita Tambunan',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            7 => 
            array (
                'id' => 495,
                'user_id' => 773,
                'customer_id' => 20728,
                'realname' => 'Umi Nasution',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            8 => 
            array (
                'id' => 496,
                'user_id' => 774,
                'customer_id' => 20729,
                'realname' => 'Dewi Tambunan',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            9 => 
            array (
                'id' => 497,
                'user_id' => 775,
                'customer_id' => 20730,
                'realname' => 'Slamet Hidayat',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            10 => 
            array (
                'id' => 498,
                'user_id' => 776,
                'customer_id' => 20731,
                'realname' => 'Kadek Lestari',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            11 => 
            array (
                'id' => 499,
                'user_id' => 777,
                'customer_id' => 20732,
                'realname' => 'Dewi Rahayu',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            12 => 
            array (
                'id' => 500,
                'user_id' => 778,
                'customer_id' => 20733,
                'realname' => 'Andi Ramadhan',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            13 => 
            array (
                'id' => 501,
                'user_id' => 779,
                'customer_id' => 20734,
                'realname' => 'Bambang Saputra',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            14 => 
            array (
                'id' => 502,
                'user_id' => 780,
                'customer_id' => 20735,
                'realname' => 'Fajar Hutapea',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            15 => 
            array (
                'id' => 503,
                'user_id' => 781,
                'customer_id' => 20736,
                'realname' => 'Fajar Sihombing',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            16 => 
            array (
                'id' => 504,
                'user_id' => 782,
                'customer_id' => 20737,
                'realname' => 'Endah Susanto',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            17 => 
            array (
                'id' => 505,
                'user_id' => 783,
                'customer_id' => 20738,
                'realname' => 'Rina Tambunan',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            18 => 
            array (
                'id' => 506,
                'user_id' => 784,
                'customer_id' => 20739,
                'realname' => 'Wahyu Silitonga',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            19 => 
            array (
                'id' => 507,
                'user_id' => 785,
                'customer_id' => 20740,
                'realname' => 'Lina Setiawan',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            20 => 
            array (
                'id' => 508,
                'user_id' => 786,
                'customer_id' => 20741,
                'realname' => 'Gita Anggraini',
                'jabatan' => 'Admin Perusahaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            21 => 
            array (
                'id' => 509,
                'user_id' => 787,
                'customer_id' => 20742,
                'realname' => 'Dewi Pratama',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            22 => 
            array (
                'id' => 510,
                'user_id' => 788,
                'customer_id' => 20743,
                'realname' => 'Andi Simanjuntak',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            23 => 
            array (
                'id' => 511,
                'user_id' => 789,
                'customer_id' => 20744,
                'realname' => 'Wahyu Santoso',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            24 => 
            array (
                'id' => 512,
                'user_id' => 790,
                'customer_id' => 20745,
                'realname' => 'Made Anggraini',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            25 => 
            array (
                'id' => 513,
                'user_id' => 791,
                'customer_id' => 20746,
                'realname' => 'Sari Maulana',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            26 => 
            array (
                'id' => 514,
                'user_id' => 792,
                'customer_id' => 20747,
                'realname' => 'Slamet Tambunan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            27 => 
            array (
                'id' => 515,
                'user_id' => 793,
                'customer_id' => 20748,
                'realname' => 'Andi Sinaga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:56',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            28 => 
            array (
                'id' => 516,
                'user_id' => 794,
                'customer_id' => 20749,
                'realname' => 'Umi Utami',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            29 => 
            array (
                'id' => 517,
                'user_id' => 795,
                'customer_id' => 20750,
                'realname' => 'Slamet Halim',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            30 => 
            array (
                'id' => 518,
                'user_id' => 796,
                'customer_id' => 20751,
                'realname' => 'Eko Utami',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            31 => 
            array (
                'id' => 519,
                'user_id' => 797,
                'customer_id' => 20752,
                'realname' => 'Cahyo Tambunan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            32 => 
            array (
                'id' => 520,
                'user_id' => 798,
                'customer_id' => 20753,
                'realname' => 'Eko Sihombing',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            33 => 
            array (
                'id' => 521,
                'user_id' => 799,
                'customer_id' => 20754,
                'realname' => 'Umi Silitonga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            34 => 
            array (
                'id' => 522,
                'user_id' => 800,
                'customer_id' => 20755,
                'realname' => 'Tono Sihombing',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            35 => 
            array (
                'id' => 523,
                'user_id' => 801,
                'customer_id' => 20756,
                'realname' => 'Zainal Nugroho',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            36 => 
            array (
                'id' => 524,
                'user_id' => 802,
                'customer_id' => 20757,
                'realname' => 'Budi Rahayu',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            37 => 
            array (
                'id' => 525,
                'user_id' => 803,
                'customer_id' => 20758,
                'realname' => 'Dedi Lestari',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            38 => 
            array (
                'id' => 526,
                'user_id' => 804,
                'customer_id' => 20759,
                'realname' => 'Endah Firmansyah',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            39 => 
            array (
                'id' => 527,
                'user_id' => 805,
                'customer_id' => 20760,
                'realname' => 'Yanti Hidayat',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            40 => 
            array (
                'id' => 528,
                'user_id' => 806,
                'customer_id' => 20761,
                'realname' => 'Cahyo Siahaan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            41 => 
            array (
                'id' => 529,
                'user_id' => 807,
                'customer_id' => 20762,
                'realname' => 'Kadek Siregar',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            42 => 
            array (
                'id' => 530,
                'user_id' => 808,
                'customer_id' => 20763,
                'realname' => 'Eko Pratama',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            43 => 
            array (
                'id' => 531,
                'user_id' => 809,
                'customer_id' => 20764,
                'realname' => 'Rina Wibowo',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            44 => 
            array (
                'id' => 532,
                'user_id' => 810,
                'customer_id' => 20765,
                'realname' => 'Made Purba',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            45 => 
            array (
                'id' => 533,
                'user_id' => 811,
                'customer_id' => 20766,
                'realname' => 'Andi Firmansyah',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            46 => 
            array (
                'id' => 534,
                'user_id' => 812,
                'customer_id' => 20767,
                'realname' => 'Endah Rahayu',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            47 => 
            array (
                'id' => 535,
                'user_id' => 813,
                'customer_id' => 20768,
                'realname' => 'Nina Nugroho',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            48 => 
            array (
                'id' => 536,
                'user_id' => 814,
                'customer_id' => 20769,
                'realname' => 'Hadi Halim',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            49 => 
            array (
                'id' => 537,
                'user_id' => 815,
                'customer_id' => 20770,
                'realname' => 'Joko Tambunan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            50 => 
            array (
                'id' => 538,
                'user_id' => 816,
                'customer_id' => 20771,
                'realname' => 'Budi Sinaga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            51 => 
            array (
                'id' => 539,
                'user_id' => 817,
                'customer_id' => 20772,
                'realname' => 'Agus Hidayat',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            52 => 
            array (
                'id' => 540,
                'user_id' => 818,
                'customer_id' => 20773,
                'realname' => 'Eko Susanto',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            53 => 
            array (
                'id' => 541,
                'user_id' => 819,
                'customer_id' => 20774,
                'realname' => 'Bambang Rahayu',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            54 => 
            array (
                'id' => 542,
                'user_id' => 820,
                'customer_id' => 20775,
                'realname' => 'Adi Purba',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            55 => 
            array (
                'id' => 543,
                'user_id' => 821,
                'customer_id' => 20776,
                'realname' => 'Ratna Sinaga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            56 => 
            array (
                'id' => 544,
                'user_id' => 822,
                'customer_id' => 20777,
                'realname' => 'Lina Tambunan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            57 => 
            array (
                'id' => 545,
                'user_id' => 823,
                'customer_id' => 20778,
                'realname' => 'Budi Lestari',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            58 => 
            array (
                'id' => 546,
                'user_id' => 824,
                'customer_id' => 20779,
                'realname' => 'Made Setiawan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            59 => 
            array (
                'id' => 547,
                'user_id' => 825,
                'customer_id' => 20780,
                'realname' => 'Umi Sinaga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            60 => 
            array (
                'id' => 548,
                'user_id' => 826,
                'customer_id' => 20781,
                'realname' => 'Lina Sinaga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            61 => 
            array (
                'id' => 549,
                'user_id' => 827,
                'customer_id' => 20782,
                'realname' => 'Dwi Simanjuntak',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            62 => 
            array (
                'id' => 550,
                'user_id' => 828,
                'customer_id' => 20783,
                'realname' => 'Made Utami',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            63 => 
            array (
                'id' => 551,
                'user_id' => 829,
                'customer_id' => 20784,
                'realname' => 'Andi Santoso',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            64 => 
            array (
                'id' => 552,
                'user_id' => 830,
                'customer_id' => 20785,
                'realname' => 'Fajar Wibowo',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            65 => 
            array (
                'id' => 553,
                'user_id' => 831,
                'customer_id' => 20786,
                'realname' => 'Putra Halim',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            66 => 
            array (
                'id' => 554,
                'user_id' => 832,
                'customer_id' => 20787,
                'realname' => 'Zainal Susanto',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            67 => 
            array (
                'id' => 555,
                'user_id' => 833,
                'customer_id' => 20788,
                'realname' => 'Yanti Silitonga',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            68 => 
            array (
                'id' => 556,
                'user_id' => 834,
                'customer_id' => 20789,
                'realname' => 'Yanti Simanjuntak',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            69 => 
            array (
                'id' => 557,
                'user_id' => 835,
                'customer_id' => 20790,
                'realname' => 'Budi Maulana',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            70 => 
            array (
                'id' => 558,
                'user_id' => 836,
                'customer_id' => 20791,
                'realname' => 'Wahyu Siregar',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            71 => 
            array (
                'id' => 559,
                'user_id' => 837,
                'customer_id' => 20792,
                'realname' => 'Adi Gunawan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            72 => 
            array (
                'id' => 560,
                'user_id' => 838,
                'customer_id' => 20793,
                'realname' => 'Bambang Simanjuntak',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            73 => 
            array (
                'id' => 561,
                'user_id' => 839,
                'customer_id' => 20794,
                'realname' => 'Rina Manullang',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            74 => 
            array (
                'id' => 562,
                'user_id' => 840,
                'customer_id' => 20795,
                'realname' => 'Slamet Ramadhan',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            75 => 
            array (
                'id' => 563,
                'user_id' => 841,
                'customer_id' => 20796,
                'realname' => 'Budi Hidayat',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            76 => 
            array (
                'id' => 564,
                'user_id' => 842,
                'customer_id' => 20797,
                'realname' => 'Gita Sihombing',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            77 => 
            array (
                'id' => 565,
                'user_id' => 843,
                'customer_id' => 20798,
                'realname' => 'Joko Nugroho',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            78 => 
            array (
                'id' => 566,
                'user_id' => 844,
                'customer_id' => 20799,
                'realname' => 'Eko Wijaya',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            79 => 
            array (
                'id' => 567,
                'user_id' => 845,
                'customer_id' => 20800,
                'realname' => 'Umi Hutapea',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            80 => 
            array (
                'id' => 568,
                'user_id' => 846,
                'customer_id' => 20801,
                'realname' => 'Agus Santoso',
                'jabatan' => 'Admin Cabang',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            81 => 
            array (
                'id' => 569,
                'user_id' => 847,
                'customer_id' => 20721,
                'realname' => 'Rudi Hartono',
                'jabatan' => 'HRD',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            82 => 
            array (
                'id' => 570,
                'user_id' => 848,
                'customer_id' => 20722,
                'realname' => 'Susi Susanti',
                'jabatan' => 'HRD',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            83 => 
            array (
                'id' => 571,
                'user_id' => 849,
                'customer_id' => 20723,
                'realname' => 'Teguh Prasetyo',
                'jabatan' => 'HRD',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            84 => 
            array (
                'id' => 572,
                'user_id' => 850,
                'customer_id' => 20724,
                'realname' => 'Dian Pertiwi',
                'jabatan' => 'Finance',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            85 => 
            array (
                'id' => 573,
                'user_id' => 851,
                'customer_id' => 20724,
                'realname' => 'Hendra Gunawan',
                'jabatan' => 'Purchasing',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            86 => 
            array (
                'id' => 574,
                'user_id' => 852,
                'customer_id' => 20724,
                'realname' => 'Ratih Kumala',
                'jabatan' => 'HRD',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            87 => 
            array (
                'id' => 575,
                'user_id' => 853,
                'customer_id' => 20725,
                'realname' => 'Rina Marlina',
                'jabatan' => 'Finance',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            88 => 
            array (
                'id' => 576,
                'user_id' => 854,
                'customer_id' => 20725,
                'realname' => 'Bowo Laksono',
                'jabatan' => 'Purchasing',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            89 => 
            array (
                'id' => 577,
                'user_id' => 855,
                'customer_id' => 20725,
                'realname' => 'Sri Wahyuni',
                'jabatan' => 'HRD',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
        ));
        
        
    }
}