<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 20721,
                'ulid' => '01m1y2aa1pk600fa7e574f7dvc',
                'code' => '16IG',
                'name' => 'PT Cipta Karya',
                'address' => NULL,
                'province_id' => 11,
                'regency_id' => 155,
                'email' => 'cust_20721@wasnaker.lan',
                'phone' => '11-5550001',
                'vat_id' => 1,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 766,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:25',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 20722,
                'ulid' => '01m1y2aab10765zwqfs8jb96gk',
                'code' => '16L5',
                'name' => 'PT Nusantara Sejahtera',
                'address' => NULL,
                'province_id' => 12,
                'regency_id' => 164,
                'email' => 'cust_20722@wasnaker.lan',
                'phone' => '12-5550002',
                'vat_id' => 5,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 767,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:25',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 20723,
                'ulid' => '01m1y2aamvyr225jy7wg4j9e6k',
                'code' => '16NU',
                'name' => 'PT Bina Marga',
                'address' => NULL,
                'province_id' => 6,
                'regency_id' => 112,
                'email' => 'cust_20723@wasnaker.lan',
                'phone' => '14-5550004',
                'vat_id' => 11,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 768,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:25',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 20724,
                'ulid' => '01m1y2abfbw5a8a425x9rygpcs',
                'code' => '16QJ',
                'name' => 'PT Jaya Abadi',
                'address' => NULL,
                'province_id' => 13,
                'regency_id' => 191,
                'email' => 'cust_20724@wasnaker.lan',
                'phone' => '13-5550003',
                'vat_id' => 8,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 769,
                'created_at' => '2026-09-07 13:53:26',
                'updated_at' => '2026-09-07 13:53:26',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 20725,
                'ulid' => '01m1y2abwtvsgqy65e2441vx2q',
                'code' => '16T8',
                'name' => 'PT Karunia Abadi',
                'address' => NULL,
                'province_id' => 11,
                'regency_id' => 156,
                'email' => 'cust_20725@wasnaker.lan',
                'phone' => '23243wqewe',
                'vat_id' => 78,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 770,
                'created_at' => '2026-09-07 13:53:26',
                'updated_at' => '2026-09-07 13:53:26',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 20726,
                'ulid' => '01m1y2ac5q0k533x4xcyvpazmm',
                'code' => '16VX',
                'name' => 'PT Mulia Bersama',
                'address' => NULL,
                'province_id' => 16,
                'regency_id' => 267,
                'email' => 'cust_20726@wasnaker.lan',
                'phone' => '16-5550006',
                'vat_id' => 18,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 771,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:27',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 20727,
                'ulid' => '01m1y2acekw9gw1v4wfr3c6vnq',
                'code' => '16YM',
                'name' => 'PT Sinar Mas',
                'address' => NULL,
                'province_id' => 15,
                'regency_id' => 231,
                'email' => 'cust_20727@wasnaker.lan',
                'phone' => '15-5550005',
                'vat_id' => 14,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 772,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:27',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 20728,
                'ulid' => '01m1y2acqdvkv3wjrd000n8yc3',
                'code' => '171B',
                'name' => 'PT Bumi Persada',
                'address' => NULL,
                'province_id' => 17,
                'regency_id' => 277,
                'email' => 'cust_20728@wasnaker.lan',
                'phone' => '17-5550007',
                'vat_id' => 22,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 773,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:27',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 20729,
                'ulid' => '01m1y2ad0a2c8qnrnanps4pbkz',
                'code' => '1740',
                'name' => 'PT Prima Utama',
                'address' => NULL,
                'province_id' => 2,
                'regency_id' => 27,
                'email' => 'cust_20729@wasnaker.lan',
                'phone' => '02-5550008',
                'vat_id' => 26,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 774,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:28',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 20730,
                'ulid' => '01m1y2ad972wy4hcyp45xjz6b4',
                'code' => '176P',
                'name' => 'PT Indah Kiat',
                'address' => NULL,
                'province_id' => 4,
                'regency_id' => 79,
                'email' => 'cust_20730@wasnaker.lan',
                'phone' => '04-5550009',
                'vat_id' => 30,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 775,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:28',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 20731,
                'ulid' => '01m1y2adj6z6kse882x8q5eh8m',
                'code' => '179E',
                'name' => 'PT Surya Gemilang',
                'address' => NULL,
                'province_id' => 27,
                'regency_id' => 402,
                'email' => 'cust_20731@wasnaker.lan',
                'phone' => '27-5550010',
                'vat_id' => 34,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 776,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:28',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 20732,
                'ulid' => '01m1y2ae4q3fy2mrhephmrr291',
                'code' => '17C3',
                'name' => 'PT Kencana Tunggal',
                'address' => NULL,
                'province_id' => 11,
                'regency_id' => 159,
                'email' => 'cust_20732@wasnaker.lan',
                'phone' => '11-5550012',
                'vat_id' => 38,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 777,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 14:06:25',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 20733,
                'ulid' => '01m1y2aee7yzbkhay7nm087972',
                'code' => '17ES',
                'name' => 'PT Harapan Jaya',
                'address' => NULL,
                'province_id' => 12,
                'regency_id' => 167,
                'email' => 'cust_20733@wasnaker.lan',
                'phone' => '12-5550012',
                'vat_id' => 42,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 778,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:29',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 20734,
                'ulid' => '01m1y2aeq2te0bc4nq9jz1gm3m',
                'code' => '17HH',
                'name' => 'PT Berkah Mandiri',
                'address' => NULL,
                'province_id' => 13,
                'regency_id' => 194,
                'email' => 'cust_20734@wasnaker.lan',
                'phone' => '13-5550013',
                'vat_id' => 46,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 779,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:29',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 20735,
                'ulid' => '01m1y2af02ahca3d6bdy7ea495',
                'code' => '17K6',
                'name' => 'PT Cahaya Nusantara',
                'address' => NULL,
                'province_id' => 6,
                'regency_id' => 112,
                'email' => 'cust_20735@wasnaker.lan',
                'phone' => '14-5550014',
                'vat_id' => 50,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 780,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:30',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 20736,
                'ulid' => '01m1y2af92can6ch5zkr82f15k',
                'code' => '17MV',
                'name' => 'PT Sentosa Abadi',
                'address' => NULL,
                'province_id' => 15,
                'regency_id' => 234,
                'email' => 'cust_20736@wasnaker.lan',
                'phone' => '15-5550015',
                'vat_id' => 54,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 781,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:30',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 20737,
                'ulid' => '01m1y2afhypf24t7y6mv1grkfs',
                'code' => '17PK',
                'name' => 'PT Mitra Sejati',
                'address' => NULL,
                'province_id' => 16,
                'regency_id' => 272,
                'email' => 'cust_20737@wasnaker.lan',
                'phone' => '16-5550016',
                'vat_id' => 58,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 782,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:30',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 20738,
                'ulid' => '01m1y2ag5k9kzzp9g7dqya9v57',
                'code' => '17S9',
                'name' => 'PT Prasetya Utama',
                'address' => NULL,
                'province_id' => 2,
                'regency_id' => 30,
                'email' => 'cust_20738@wasnaker.lan',
                'phone' => '02-5550018',
                'vat_id' => 66,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 783,
                'created_at' => '2026-09-07 13:53:31',
                'updated_at' => '2026-09-07 13:53:31',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20739,
                'ulid' => '01m1y2agqhwvnccxsq4m36t94q',
                'code' => '17UY',
                'name' => 'PT Wijaya Karya',
                'address' => NULL,
                'province_id' => 17,
                'regency_id' => 281,
                'email' => 'cust_20739@wasnaker.lan',
                'phone' => '17-5550017',
                'vat_id' => 62,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 784,
                'created_at' => '2026-09-07 13:53:31',
                'updated_at' => '2026-09-07 13:53:31',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20740,
                'ulid' => '01m1y2ah98fdvy0v0a15ymn7ef',
                'code' => '17XN',
                'name' => 'PT Bhakti Nusantara',
                'address' => NULL,
                'province_id' => 4,
                'regency_id' => 82,
                'email' => 'cust_20740@wasnaker.lan',
                'phone' => '04-5550019',
                'vat_id' => 70,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 785,
                'created_at' => '2026-09-07 13:53:32',
                'updated_at' => '2026-09-07 13:53:32',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 20741,
                'ulid' => '01m1y2aj0yrqy6krb504jgsfvt',
                'code' => '180C',
                'name' => 'PT Sukses Mandiri',
                'address' => NULL,
                'province_id' => 27,
                'regency_id' => 405,
                'email' => 'cust_20741@wasnaker.lan',
                'phone' => '27-5550020',
                'vat_id' => 74,
                'type' => 'customer',
                'parent_id' => NULL,
                'is_active' => 1,
                'admin_id' => 786,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:33',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 20742,
                'ulid' => '01m1y2ajaw81bvtynpv25ycpz5',
                'code' => '1831',
                'name' => 'PT Cipta Karya - Cabang Jawa Barat',
                'address' => 'Jl. Contoh No. 00, Jawa Barat',
                'province_id' => 12,
                'regency_id' => 161,
                'email' => 'cust_20742@wasnaker.lan',
                'phone' => '12-6660101',
                'vat_id' => 3,
                'type' => 'branch',
                'parent_id' => 20721,
                'is_active' => 1,
                'admin_id' => 787,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:33',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 20743,
                'ulid' => '01m1y2ajkppy9xm8sbphg6qd7a',
                'code' => '185Q',
                'name' => 'PT Nusantara Sejahtera - Cabang Jawa Tengah',
                'address' => 'Jl. Contoh No. 10, Jawa Tengah',
                'province_id' => 13,
                'regency_id' => 188,
                'email' => 'cust_20743@wasnaker.lan',
                'phone' => '13-6660201',
                'vat_id' => 6,
                'type' => 'branch',
                'parent_id' => 20722,
                'is_active' => 1,
                'admin_id' => 788,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:33',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 20744,
                'ulid' => '01m1y2ajwpgzcn6bvcpkjbdkc7',
                'code' => '188F',
                'name' => 'PT Cipta Karya - Plant Jawa Tengah',
                'address' => 'Jl. Contoh No. 01, Jawa Tengah',
                'province_id' => 13,
                'regency_id' => 188,
                'email' => 'cust_20744@wasnaker.lan',
                'phone' => '13-6660102',
                'vat_id' => 4,
                'type' => 'branch',
                'parent_id' => 20721,
                'is_active' => 1,
                'admin_id' => 789,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:34',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 20745,
                'ulid' => '01m1y2ak5mpkwb48wc8xzk0qav',
                'code' => '18B4',
                'name' => 'PT Nusantara Sejahtera - Plant DI Yogyakarta',
                'address' => 'Jl. Contoh No. 11, DI Yogyakarta',
                'province_id' => 14,
                'regency_id' => 223,
                'email' => 'cust_20745@wasnaker.lan',
                'phone' => '14-6660202',
                'vat_id' => 7,
                'type' => 'branch',
                'parent_id' => 20722,
                'is_active' => 1,
                'admin_id' => 790,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:34',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 20746,
                'ulid' => '01m1y2akefn9gd1n51na0f51zk',
                'code' => '18DT',
                'name' => 'PT Cipta Karya - Site DI Yogyakarta',
                'address' => 'Jl. Contoh No. 02, DI Yogyakarta',
                'province_id' => 14,
                'regency_id' => 223,
                'email' => 'cust_20746@wasnaker.lan',
                'phone' => '14-6660103',
                'vat_id' => 79,
                'type' => 'branch',
                'parent_id' => 20721,
                'is_active' => 1,
                'admin_id' => 791,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:34',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 20747,
                'ulid' => '01m1y2akqadnszd9smpcbyfn6f',
                'code' => '18GI',
                'name' => 'PT Nusantara Sejahtera - Site Jawa Timur',
                'address' => 'Jl. Contoh No. 12, Jawa Timur',
                'province_id' => 15,
                'regency_id' => 228,
                'email' => 'cust_20747@wasnaker.lan',
                'phone' => '15-6660203',
                'vat_id' => 80,
                'type' => 'branch',
                'parent_id' => 20722,
                'is_active' => 1,
                'admin_id' => 792,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:34',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 20748,
                'ulid' => '01m1y2am06vd4g1frrdfweba63',
                'code' => '18J7',
                'name' => 'PT Jaya Abadi - Cabang DI Yogyakarta',
                'address' => 'Jl. Contoh No. 20, DI Yogyakarta',
                'province_id' => 14,
                'regency_id' => 223,
                'email' => 'cust_20748@wasnaker.lan',
                'phone' => '14-6660301',
                'vat_id' => 8,
                'type' => 'branch',
                'parent_id' => 20724,
                'is_active' => 1,
                'admin_id' => 793,
                'created_at' => '2026-09-07 13:53:35',
                'updated_at' => '2026-09-07 13:53:35',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 20749,
                'ulid' => '01m1y2amjp259p4hsyzfwb5j5x',
                'code' => '18LW',
                'name' => 'PT Bina Marga - Cabang Sumatera Selatan',
                'address' => 'Jl. Contoh No. 30, Jawa Timur',
                'province_id' => 6,
                'regency_id' => 99,
                'email' => 'cust_20749@wasnaker.lan',
                'phone' => '15-6660401',
                'vat_id' => 13,
                'type' => 'branch',
                'parent_id' => 20723,
                'is_active' => 1,
                'admin_id' => 794,
                'created_at' => '2026-09-07 13:53:35',
                'updated_at' => '2026-09-07 13:53:35',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 20750,
                'ulid' => '01m1y2amvq6715emynrfea7bcg',
                'code' => '18OL',
                'name' => 'PT Jaya Abadi - Plant Jawa Timur',
                'address' => 'Jl. Contoh No. 21, Jawa Timur',
                'province_id' => 15,
                'regency_id' => 228,
                'email' => 'cust_20750@wasnaker.lan',
                'phone' => '15-6660302',
                'vat_id' => 10,
                'type' => 'branch',
                'parent_id' => 20724,
                'is_active' => 1,
                'admin_id' => 795,
                'created_at' => '2026-09-07 13:53:36',
                'updated_at' => '2026-09-07 13:53:36',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 20751,
                'ulid' => '01m1y2anbzqaygn8v0t5n34gvn',
                'code' => '18RA',
                'name' => 'PT Bina Marga - Plant Sumatera Selatan',
                'address' => 'Jl. Contoh No. 31, Banten',
                'province_id' => 6,
                'regency_id' => 102,
                'email' => 'cust_20751@wasnaker.lan',
                'phone' => '16-6660402',
                'vat_id' => 11,
                'type' => 'branch',
                'parent_id' => 20723,
                'is_active' => 1,
                'admin_id' => 796,
                'created_at' => '2026-09-07 13:53:36',
                'updated_at' => '2026-09-07 13:53:36',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 20752,
                'ulid' => '01m1y2ap33dn1z2hgtt0qz8bff',
                'code' => '18TZ',
                'name' => 'PT Jaya Abadi - Site Banten',
                'address' => 'Jl. Contoh No. 22, Banten',
                'province_id' => 16,
                'regency_id' => 266,
                'email' => 'cust_20752@wasnaker.lan',
                'phone' => '16-6660303',
                'vat_id' => 81,
                'type' => 'branch',
                'parent_id' => 20724,
                'is_active' => 1,
                'admin_id' => 797,
                'created_at' => '2026-09-07 13:53:37',
                'updated_at' => '2026-09-07 13:53:37',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 20753,
                'ulid' => '01m1y2apmm0t8xbk09drh5qfc8',
                'code' => '18WO',
                'name' => 'PT Bina Marga - Site Sumatera Selatan',
                'address' => 'Jl. Contoh No. 32, Bali',
                'province_id' => 6,
                'regency_id' => 105,
                'email' => 'cust_20753@wasnaker.lan',
                'phone' => '17-6660403',
                'vat_id' => 82,
                'type' => 'branch',
                'parent_id' => 20723,
                'is_active' => 1,
                'admin_id' => 798,
                'created_at' => '2026-09-07 13:53:37',
                'updated_at' => '2026-09-07 13:53:37',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 20754,
                'ulid' => '01m1y2aq3ym060tr38pfddzwb0',
                'code' => '18ZD',
                'name' => 'PT Sinar Mas - Cabang Banten',
                'address' => 'Jl. Contoh No. 40, Banten',
                'province_id' => 16,
                'regency_id' => 266,
                'email' => 'cust_20754@wasnaker.lan',
                'phone' => '16-6660501',
                'vat_id' => 16,
                'type' => 'branch',
                'parent_id' => 20727,
                'is_active' => 1,
                'admin_id' => 799,
                'created_at' => '2026-09-07 13:53:38',
                'updated_at' => '2026-09-07 13:53:38',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 20755,
                'ulid' => '01m1y2aqhxvgwg8114sxvbaks7',
                'code' => '1922',
                'name' => 'PT Mulia Bersama - Cabang Bali',
                'address' => 'Jl. Contoh No. 50, Bali',
                'province_id' => 17,
                'regency_id' => 274,
                'email' => 'cust_20755@wasnaker.lan',
                'phone' => '17-6660601',
                'vat_id' => 20,
                'type' => 'branch',
                'parent_id' => 20726,
                'is_active' => 1,
                'admin_id' => 800,
                'created_at' => '2026-09-07 13:53:38',
                'updated_at' => '2026-09-07 13:53:38',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 20756,
                'ulid' => '01m1y2aqyhh3hz728xp1x6yct3',
                'code' => '194R',
                'name' => 'PT Sinar Mas - Plant Bali',
                'address' => 'Jl. Contoh No. 41, Bali',
                'province_id' => 17,
                'regency_id' => 274,
                'email' => 'cust_20756@wasnaker.lan',
                'phone' => '17-6660502',
                'vat_id' => 17,
                'type' => 'branch',
                'parent_id' => 20727,
                'is_active' => 1,
                'admin_id' => 801,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:39',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 20757,
                'ulid' => '01m1y2ar7h95tst5c5sjc4n0e1',
                'code' => '197G',
                'name' => 'PT Mulia Bersama - Plant Sumatera Utara',
                'address' => 'Jl. Contoh No. 51, Sumatera Utara',
                'province_id' => 2,
                'regency_id' => 24,
                'email' => 'cust_20757@wasnaker.lan',
                'phone' => '02-6660602',
                'vat_id' => 21,
                'type' => 'branch',
                'parent_id' => 20726,
                'is_active' => 1,
                'admin_id' => 802,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:39',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 20758,
                'ulid' => '01m1y2argdjbtf5qvhqev6qg7g',
                'code' => '19A5',
                'name' => 'PT Sinar Mas - Site Sumatera Utara',
                'address' => 'Jl. Contoh No. 42, Sumatera Utara',
                'province_id' => 2,
                'regency_id' => 24,
                'email' => 'cust_20758@wasnaker.lan',
                'phone' => '02-6660503',
                'vat_id' => 14,
                'type' => 'branch',
                'parent_id' => 20727,
                'is_active' => 1,
                'admin_id' => 803,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:39',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 20759,
                'ulid' => '01m1y2arsfhw9nbsx6jghsjm1e',
                'code' => '19CU',
                'name' => 'PT Mulia Bersama - Site Riau',
                'address' => 'Jl. Contoh No. 52, Riau',
                'province_id' => 4,
                'regency_id' => 76,
                'email' => 'cust_20759@wasnaker.lan',
                'phone' => '04-6660603',
                'vat_id' => 83,
                'type' => 'branch',
                'parent_id' => 20726,
                'is_active' => 1,
                'admin_id' => 804,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:40',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 20760,
                'ulid' => '01m1y2as2f6w4wrpyhkjtrwgx4',
                'code' => '19FJ',
                'name' => 'PT Prima Utama - Cabang Riau',
                'address' => 'Jl. Contoh No. 70, Riau',
                'province_id' => 4,
                'regency_id' => 76,
                'email' => 'cust_20760@wasnaker.lan',
                'phone' => '04-6660801',
                'vat_id' => 28,
                'type' => 'branch',
                'parent_id' => 20729,
                'is_active' => 1,
                'admin_id' => 805,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:40',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 20761,
                'ulid' => '01m1y2asbc4dwmbm6c8tfc72cw',
                'code' => '19I8',
                'name' => 'PT Bumi Persada - Cabang Sumatera Utara',
                'address' => 'Jl. Contoh No. 60, Sumatera Utara',
                'province_id' => 2,
                'regency_id' => 24,
                'email' => 'cust_20761@wasnaker.lan',
                'phone' => '02-6660701',
                'vat_id' => 24,
                'type' => 'branch',
                'parent_id' => 20728,
                'is_active' => 1,
                'admin_id' => 806,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:40',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 20762,
                'ulid' => '01m1y2at0y3r7dwf2qcncm1w1k',
                'code' => '19KX',
                'name' => 'PT Bumi Persada - Plant Riau',
                'address' => 'Jl. Contoh No. 61, Riau',
                'province_id' => 4,
                'regency_id' => 76,
                'email' => 'cust_20762@wasnaker.lan',
                'phone' => '04-6660702',
                'vat_id' => 25,
                'type' => 'branch',
                'parent_id' => 20728,
                'is_active' => 1,
                'admin_id' => 807,
                'created_at' => '2026-09-07 13:53:41',
                'updated_at' => '2026-09-07 13:53:41',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 20763,
                'ulid' => '01m1y2atgsd9vx2c6jwwchd0zn',
                'code' => '19NM',
                'name' => 'PT Prima Utama - Plant Sulawesi Selatan',
                'address' => 'Jl. Contoh No. 71, Sulawesi Selatan',
                'province_id' => 27,
                'regency_id' => 399,
                'email' => 'cust_20763@wasnaker.lan',
                'phone' => '27-6660802',
                'vat_id' => 29,
                'type' => 'branch',
                'parent_id' => 20729,
                'is_active' => 1,
                'admin_id' => 808,
                'created_at' => '2026-09-07 13:53:41',
                'updated_at' => '2026-09-07 13:53:41',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 20764,
                'ulid' => '01m1y2atsxdbzz1gnh1f0a7nf1',
                'code' => '19QB',
                'name' => 'PT Bumi Persada - Site Sulawesi Selatan',
                'address' => 'Jl. Contoh No. 62, Sulawesi Selatan',
                'province_id' => 27,
                'regency_id' => 399,
                'email' => 'cust_20764@wasnaker.lan',
                'phone' => '27-6660703',
                'vat_id' => 84,
                'type' => 'branch',
                'parent_id' => 20728,
                'is_active' => 1,
                'admin_id' => 809,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:42',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 20765,
                'ulid' => '01m1y2av2vfc5t0mqc5ss0bvcy',
                'code' => '19T0',
                'name' => 'PT Prima Utama - Site DKI Jakarta',
                'address' => 'Jl. Contoh No. 72, DKI Jakarta',
                'province_id' => 11,
                'regency_id' => 155,
                'email' => 'cust_20765@wasnaker.lan',
                'phone' => '11-6660803',
                'vat_id' => 85,
                'type' => 'branch',
                'parent_id' => 20729,
                'is_active' => 1,
                'admin_id' => 810,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:42',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 20766,
                'ulid' => '01m1y2avbrbz7s6zja1c1qfyve',
                'code' => '19VP',
                'name' => 'PT Indah Kiat - Cabang Sulawesi Selatan',
                'address' => 'Jl. Contoh No. 80, Sulawesi Selatan',
                'province_id' => 27,
                'regency_id' => 399,
                'email' => 'cust_20766@wasnaker.lan',
                'phone' => '27-6660901',
                'vat_id' => 32,
                'type' => 'branch',
                'parent_id' => 20730,
                'is_active' => 1,
                'admin_id' => 811,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:42',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 20767,
                'ulid' => '01m1y2avmqdpg6b1sy6dsnzn79',
                'code' => '19YE',
                'name' => 'PT Surya Gemilang - Cabang DKI Jakarta',
                'address' => 'Jl. Contoh No. 90, DKI Jakarta',
                'province_id' => 11,
                'regency_id' => 156,
                'email' => 'cust_20767@wasnaker.lan',
                'phone' => '11-6661001',
                'vat_id' => 36,
                'type' => 'branch',
                'parent_id' => 20731,
                'is_active' => 1,
                'admin_id' => 812,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:43',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 20768,
                'ulid' => '01m1y2avxx4c1hxmr6y46q979d',
                'code' => '1A13',
                'name' => 'PT Indah Kiat - Plant DKI Jakarta',
                'address' => 'Jl. Contoh No. 81, DKI Jakarta',
                'province_id' => 11,
                'regency_id' => 155,
                'email' => 'cust_20768@wasnaker.lan',
                'phone' => '11-6660902',
                'vat_id' => 33,
                'type' => 'branch',
                'parent_id' => 20730,
                'is_active' => 1,
                'admin_id' => 813,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:43',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 20769,
                'ulid' => '01m1y2aw6sr2vzjwpwrm6ttvn8',
                'code' => '1A3S',
                'name' => 'PT Surya Gemilang - Plant Jawa Barat',
                'address' => 'Jl. Contoh No. 91, Jawa Barat',
                'province_id' => 12,
                'regency_id' => 163,
                'email' => 'cust_20769@wasnaker.lan',
                'phone' => '12-6661002',
                'vat_id' => 37,
                'type' => 'branch',
                'parent_id' => 20731,
                'is_active' => 1,
                'admin_id' => 814,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:43',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 20770,
                'ulid' => '01m1y2awfmzbjaz8gk935brk5w',
                'code' => '1A6H',
                'name' => 'PT Indah Kiat - Site Jawa Barat',
                'address' => 'Jl. Contoh No. 82, Jawa Barat',
                'province_id' => 12,
                'regency_id' => 161,
                'email' => 'cust_20770@wasnaker.lan',
                'phone' => '12-6660903',
                'vat_id' => 86,
                'type' => 'branch',
                'parent_id' => 20730,
                'is_active' => 1,
                'admin_id' => 815,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:43',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 20771,
                'ulid' => '01m1y2awrsat1a3cc6y1fngdta',
                'code' => '1A96',
                'name' => 'PT Surya Gemilang - Site Jawa Tengah',
                'address' => 'Jl. Contoh No. 92, Jawa Tengah',
                'province_id' => 13,
                'regency_id' => 188,
                'email' => 'cust_20771@wasnaker.lan',
                'phone' => '13-6661003',
                'vat_id' => 87,
                'type' => 'branch',
                'parent_id' => 20731,
                'is_active' => 1,
                'admin_id' => 816,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:44',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 20772,
                'ulid' => '01m1y2ax26kz7b1sm0g82vy5ra',
                'code' => '1ABV',
                'name' => 'PT Kencana Tunggal - Cabang Jawa Barat',
                'address' => 'Jl. Contoh No. 100, Jawa Barat',
                'province_id' => 12,
                'regency_id' => 161,
                'email' => 'cust_20772@wasnaker.lan',
                'phone' => '12-6661101',
                'vat_id' => 40,
                'type' => 'branch',
                'parent_id' => 20732,
                'is_active' => 1,
                'admin_id' => 817,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:44',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 20773,
                'ulid' => '01m1y2axecdn05r78m0hnta4e4',
                'code' => '1AEK',
                'name' => 'PT Harapan Jaya - Cabang Jawa Tengah',
                'address' => 'Jl. Contoh No. 110, Jawa Tengah',
                'province_id' => 13,
                'regency_id' => 188,
                'email' => 'cust_20773@wasnaker.lan',
                'phone' => '13-6661201',
                'vat_id' => 44,
                'type' => 'branch',
                'parent_id' => 20733,
                'is_active' => 1,
                'admin_id' => 818,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:44',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 20774,
                'ulid' => '01m1y2ay3y3h5fcbnjxersrbkk',
                'code' => '1AH9',
                'name' => 'PT Kencana Tunggal - Plant Jawa Tengah',
                'address' => 'Jl. Contoh No. 101, Jawa Tengah',
                'province_id' => 13,
                'regency_id' => 188,
                'email' => 'cust_20774@wasnaker.lan',
                'phone' => '13-6661102',
                'vat_id' => 41,
                'type' => 'branch',
                'parent_id' => 20732,
                'is_active' => 1,
                'admin_id' => 819,
                'created_at' => '2026-09-07 13:53:45',
                'updated_at' => '2026-09-07 13:53:45',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 20775,
                'ulid' => '01m1y2aym63fe7xnc8z056aayx',
                'code' => '1AJY',
                'name' => 'PT Harapan Jaya - Plant DI Yogyakarta',
                'address' => 'Jl. Contoh No. 111, DI Yogyakarta',
                'province_id' => 14,
                'regency_id' => 223,
                'email' => 'cust_20775@wasnaker.lan',
                'phone' => '14-6661202',
                'vat_id' => 45,
                'type' => 'branch',
                'parent_id' => 20733,
                'is_active' => 1,
                'admin_id' => 820,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:46',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 20776,
                'ulid' => '01m1y2ayz36qp17xd6t1kvngje',
                'code' => '1AMN',
                'name' => 'PT Kencana Tunggal - Site DI Yogyakarta',
                'address' => 'Jl. Contoh No. 102, DI Yogyakarta',
                'province_id' => 14,
                'regency_id' => 223,
                'email' => 'cust_20776@wasnaker.lan',
                'phone' => '14-6661103',
                'vat_id' => 88,
                'type' => 'branch',
                'parent_id' => 20732,
                'is_active' => 1,
                'admin_id' => 821,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:46',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 20777,
                'ulid' => '01m1y2az7yx5dgxzqer4m4c05m',
                'code' => '1APC',
                'name' => 'PT Harapan Jaya - Site Jawa Timur',
                'address' => 'Jl. Contoh No. 112, Jawa Timur',
                'province_id' => 15,
                'regency_id' => 228,
                'email' => 'cust_20777@wasnaker.lan',
                'phone' => '15-6661203',
                'vat_id' => 89,
                'type' => 'branch',
                'parent_id' => 20733,
                'is_active' => 1,
                'admin_id' => 822,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:46',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 20778,
                'ulid' => '01m1y2azgvhv7cxy78qejdnsth',
                'code' => '1AS1',
                'name' => 'PT Berkah Mandiri - Cabang DI Yogyakarta',
                'address' => 'Jl. Contoh No. 120, DI Yogyakarta',
                'province_id' => 14,
                'regency_id' => 223,
                'email' => 'cust_20778@wasnaker.lan',
                'phone' => '14-6661301',
                'vat_id' => 48,
                'type' => 'branch',
                'parent_id' => 20734,
                'is_active' => 1,
                'admin_id' => 823,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:47',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 20779,
                'ulid' => '01m1y2azsy4xvp81wcf5j694np',
                'code' => '1AUQ',
                'name' => 'PT Cahaya Nusantara - Cabang Sumatera Selatan',
                'address' => 'Jl. Contoh No. 130, Jawa Timur',
                'province_id' => 6,
                'regency_id' => 99,
                'email' => 'cust_20779@wasnaker.lan',
                'phone' => '15-6661401',
                'vat_id' => 52,
                'type' => 'branch',
                'parent_id' => 20735,
                'is_active' => 1,
                'admin_id' => 824,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:47',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 20780,
                'ulid' => '01m1y2b02wdq3tp30f4f93f0dw',
                'code' => '1AXF',
                'name' => 'PT Cahaya Nusantara - Plant Sumatera Selatan',
                'address' => 'Jl. Contoh No. 131, Banten',
                'province_id' => 6,
                'regency_id' => 102,
                'email' => 'cust_20780@wasnaker.lan',
                'phone' => '16-6661402',
                'vat_id' => 53,
                'type' => 'branch',
                'parent_id' => 20735,
                'is_active' => 1,
                'admin_id' => 825,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:47',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 20781,
                'ulid' => '01m1y2b0jvv91rb8p5tm0tphxr',
                'code' => '1B04',
                'name' => 'PT Berkah Mandiri - Plant Jawa Timur',
                'address' => 'Jl. Contoh No. 121, Jawa Timur',
                'province_id' => 15,
                'regency_id' => 228,
                'email' => 'cust_20781@wasnaker.lan',
                'phone' => '15-6661302',
                'vat_id' => 49,
                'type' => 'branch',
                'parent_id' => 20734,
                'is_active' => 1,
                'admin_id' => 826,
                'created_at' => '2026-09-07 13:53:48',
                'updated_at' => '2026-09-07 13:53:48',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 20782,
                'ulid' => '01m1y2b186cbenhn6wne85pj0k',
                'code' => '1B2T',
                'name' => 'PT Berkah Mandiri - Site Banten',
                'address' => 'Jl. Contoh No. 122, Banten',
                'province_id' => 16,
                'regency_id' => 266,
                'email' => 'cust_20782@wasnaker.lan',
                'phone' => '16-6661303',
                'vat_id' => 90,
                'type' => 'branch',
                'parent_id' => 20734,
                'is_active' => 1,
                'admin_id' => 827,
                'created_at' => '2026-09-07 13:53:48',
                'updated_at' => '2026-09-07 13:53:48',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 20783,
                'ulid' => '01m1y2b1h9k6zqekrchd8xdvrn',
                'code' => '1B5I',
                'name' => 'PT Cahaya Nusantara - Site Sumatera Selatan',
                'address' => 'Jl. Contoh No. 132, Bali',
                'province_id' => 6,
                'regency_id' => 105,
                'email' => 'cust_20783@wasnaker.lan',
                'phone' => '17-6661403',
                'vat_id' => 91,
                'type' => 'branch',
                'parent_id' => 20735,
                'is_active' => 1,
                'admin_id' => 828,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:49',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 20784,
                'ulid' => '01m1y2b1xthm449mftbs74w9px',
                'code' => '1B87',
                'name' => 'PT Sentosa Abadi - Cabang Banten',
                'address' => 'Jl. Contoh No. 140, Banten',
                'province_id' => 16,
                'regency_id' => 266,
                'email' => 'cust_20784@wasnaker.lan',
                'phone' => '16-6661501',
                'vat_id' => 56,
                'type' => 'branch',
                'parent_id' => 20736,
                'is_active' => 1,
                'admin_id' => 829,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:49',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 20785,
                'ulid' => '01m1y2b2aam71v399h07am6a12',
                'code' => '1BAW',
                'name' => 'PT Mitra Sejati - Cabang Bali',
                'address' => 'Jl. Contoh No. 150, Bali',
                'province_id' => 17,
                'regency_id' => 274,
                'email' => 'cust_20785@wasnaker.lan',
                'phone' => '17-6661601',
                'vat_id' => 60,
                'type' => 'branch',
                'parent_id' => 20737,
                'is_active' => 1,
                'admin_id' => 830,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:49',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 20786,
                'ulid' => '01m1y2b2k8re9372jr98wt548y',
                'code' => '1BDL',
                'name' => 'PT Sentosa Abadi - Plant Bali',
                'address' => 'Jl. Contoh No. 141, Bali',
                'province_id' => 17,
                'regency_id' => 274,
                'email' => 'cust_20786@wasnaker.lan',
                'phone' => '17-6661502',
                'vat_id' => 57,
                'type' => 'branch',
                'parent_id' => 20736,
                'is_active' => 1,
                'admin_id' => 831,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:50',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 20787,
                'ulid' => '01m1y2b2wmb6q2jszgjmm22aee',
                'code' => '1BGA',
                'name' => 'PT Mitra Sejati - Plant Sumatera Utara',
                'address' => 'Jl. Contoh No. 151, Sumatera Utara',
                'province_id' => 2,
                'regency_id' => 24,
                'email' => 'cust_20787@wasnaker.lan',
                'phone' => '02-6661602',
                'vat_id' => 61,
                'type' => 'branch',
                'parent_id' => 20737,
                'is_active' => 1,
                'admin_id' => 832,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:50',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 20788,
                'ulid' => '01m1y2b3605sj240wnwhfp9b8v',
                'code' => '1BIZ',
                'name' => 'PT Sentosa Abadi - Site Sumatera Utara',
                'address' => 'Jl. Contoh No. 142, Sumatera Utara',
                'province_id' => 2,
                'regency_id' => 24,
                'email' => 'cust_20788@wasnaker.lan',
                'phone' => '02-6661503',
                'vat_id' => 92,
                'type' => 'branch',
                'parent_id' => 20736,
                'is_active' => 1,
                'admin_id' => 833,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:50',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 20789,
                'ulid' => '01m1y2b3exz0qn7b2mzxjez95w',
                'code' => '1BLO',
                'name' => 'PT Mitra Sejati - Site Riau',
                'address' => 'Jl. Contoh No. 152, Riau',
                'province_id' => 4,
                'regency_id' => 76,
                'email' => 'cust_20789@wasnaker.lan',
                'phone' => '04-6661603',
                'vat_id' => 93,
                'type' => 'branch',
                'parent_id' => 20737,
                'is_active' => 1,
                'admin_id' => 834,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:51',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 20790,
                'ulid' => '01m1y2b3r2gp74bx94weq7rett',
                'code' => '1BOD',
                'name' => 'PT Prasetya Utama - Cabang Riau',
                'address' => 'Jl. Contoh No. 170, Riau',
                'province_id' => 4,
                'regency_id' => 76,
                'email' => 'cust_20790@wasnaker.lan',
                'phone' => '04-6661801',
                'vat_id' => 68,
                'type' => 'branch',
                'parent_id' => 20738,
                'is_active' => 1,
                'admin_id' => 835,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:51',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 20791,
                'ulid' => '01m1y2b40zbv0xqa0j40n1bbpx',
                'code' => '1BR2',
                'name' => 'PT Wijaya Karya - Cabang Sumatera Utara',
                'address' => 'Jl. Contoh No. 160, Sumatera Utara',
                'province_id' => 2,
                'regency_id' => 24,
                'email' => 'cust_20791@wasnaker.lan',
                'phone' => '02-6661701',
                'vat_id' => 64,
                'type' => 'branch',
                'parent_id' => 20739,
                'is_active' => 1,
                'admin_id' => 836,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:51',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 20792,
                'ulid' => '01m1y2b49zyrjmz2ce2g4g90t9',
                'code' => '1BTR',
                'name' => 'PT Wijaya Karya - Plant Riau',
                'address' => 'Jl. Contoh No. 161, Riau',
                'province_id' => 4,
                'regency_id' => 76,
                'email' => 'cust_20792@wasnaker.lan',
                'phone' => '04-6661702',
                'vat_id' => 65,
                'type' => 'branch',
                'parent_id' => 20739,
                'is_active' => 1,
                'admin_id' => 837,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:51',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 20793,
                'ulid' => '01m1y2b4kch7wnt0jr1smqqxh3',
                'code' => '1BWG',
                'name' => 'PT Prasetya Utama - Plant Sulawesi Selatan',
                'address' => 'Jl. Contoh No. 171, Sulawesi Selatan',
                'province_id' => 27,
                'regency_id' => 399,
                'email' => 'cust_20793@wasnaker.lan',
                'phone' => '27-6661802',
                'vat_id' => 69,
                'type' => 'branch',
                'parent_id' => 20738,
                'is_active' => 1,
                'admin_id' => 838,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:52',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 20794,
                'ulid' => '01m1y2b4w75y23erev1c5cyg78',
                'code' => '1BZ5',
                'name' => 'PT Wijaya Karya - Site Sulawesi Selatan',
                'address' => 'Jl. Contoh No. 162, Sulawesi Selatan',
                'province_id' => 27,
                'regency_id' => 399,
                'email' => 'cust_20794@wasnaker.lan',
                'phone' => '27-6661703',
                'vat_id' => 94,
                'type' => 'branch',
                'parent_id' => 20739,
                'is_active' => 1,
                'admin_id' => 839,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:52',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 20795,
                'ulid' => '01m1y2b5529b6a5w7hrt54td5t',
                'code' => '1C1U',
                'name' => 'PT Prasetya Utama - Site DKI Jakarta',
                'address' => 'Jl. Contoh No. 172, DKI Jakarta',
                'province_id' => 11,
                'regency_id' => 155,
                'email' => 'cust_20795@wasnaker.lan',
                'phone' => '11-6661803',
                'vat_id' => 95,
                'type' => 'branch',
                'parent_id' => 20738,
                'is_active' => 1,
                'admin_id' => 840,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:52',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 20796,
                'ulid' => '01m1y2b5e0r9t3xjpzk1akyn7e',
                'code' => '1C4J',
                'name' => 'PT Bhakti Nusantara - Cabang Sulawesi Selatan',
                'address' => 'Jl. Contoh No. 180, Sulawesi Selatan',
                'province_id' => 27,
                'regency_id' => 399,
                'email' => 'cust_20796@wasnaker.lan',
                'phone' => '27-6661901',
                'vat_id' => 72,
                'type' => 'branch',
                'parent_id' => 20740,
                'is_active' => 1,
                'admin_id' => 841,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:53',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 20797,
                'ulid' => '01m1y2b5q5g6dp3kzdhdes471j',
                'code' => '1C78',
                'name' => 'PT Sukses Mandiri - Cabang DKI Jakarta',
                'address' => 'Jl. Contoh No. 190, DKI Jakarta',
                'province_id' => 11,
                'regency_id' => 157,
                'email' => 'cust_20797@wasnaker.lan',
                'phone' => '11-6662001',
                'vat_id' => 76,
                'type' => 'branch',
                'parent_id' => 20741,
                'is_active' => 1,
                'admin_id' => 842,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:53',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 20798,
                'ulid' => '01m1y2b6026y1cmb6xtwqc6arx',
                'code' => '1C9X',
                'name' => 'PT Bhakti Nusantara - Plant DKI Jakarta',
                'address' => 'Jl. Contoh No. 181, DKI Jakarta',
                'province_id' => 11,
                'regency_id' => 155,
                'email' => 'cust_20798@wasnaker.lan',
                'phone' => '11-6661902',
                'vat_id' => 73,
                'type' => 'branch',
                'parent_id' => 20740,
                'is_active' => 1,
                'admin_id' => 843,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:53',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 20799,
                'ulid' => '01m1y2b69avst054rffbhesdy2',
                'code' => '1CCM',
                'name' => 'PT Sukses Mandiri - Plant Jawa Barat',
                'address' => 'Jl. Contoh No. 191, Jawa Barat',
                'province_id' => 12,
                'regency_id' => 162,
                'email' => 'cust_20799@wasnaker.lan',
                'phone' => '12-6662002',
                'vat_id' => 77,
                'type' => 'branch',
                'parent_id' => 20741,
                'is_active' => 1,
                'admin_id' => 844,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:53',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 20800,
                'ulid' => '01m1y2b6k5n070mp7aha2gn1zh',
                'code' => '1CFB',
                'name' => 'PT Bhakti Nusantara - Site Jawa Barat',
                'address' => 'Jl. Contoh No. 182, Jawa Barat',
                'province_id' => 12,
                'regency_id' => 161,
                'email' => 'cust_20800@wasnaker.lan',
                'phone' => '12-6661903',
                'vat_id' => 96,
                'type' => 'branch',
                'parent_id' => 20740,
                'is_active' => 1,
                'admin_id' => 845,
                'created_at' => '2026-09-07 13:53:54',
                'updated_at' => '2026-09-07 13:53:54',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 20801,
                'ulid' => '01m1y2b6wafptkmz2jdapb3864',
                'code' => '1CI0',
                'name' => 'PT Sukses Mandiri - Site Jawa Tengah',
                'address' => 'Jl. Contoh No. 192, Jawa Tengah',
                'province_id' => 13,
                'regency_id' => 188,
                'email' => 'cust_20801@wasnaker.lan',
                'phone' => '13-6662003',
                'vat_id' => 97,
                'type' => 'branch',
                'parent_id' => 20741,
                'is_active' => 1,
                'admin_id' => 846,
                'created_at' => '2026-09-07 13:53:54',
                'updated_at' => '2026-09-07 13:53:54',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}