<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Administrator',
                'email' => 'admin@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$M0tsbqj.l0Ke/Zef79bNvOHk1RjBwCUKydej.h120M7sXqQYwy09q',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 09:31:16',
                'updated_at' => '2026-09-07 09:31:16',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Demo User',
                'email' => 'demo@spine.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$39k2sAlE/02QwPPx.8x5SeGL2Dp7rXJ1ThbwJlRoSxzwrK4fVmYIq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 09:31:16',
                'updated_at' => '2026-09-07 09:31:16',
            ),
            2 => 
            array (
                'id' => 766,
                'name' => 'budi-sihombing',
                'email' => 'budi-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            3 => 
            array (
                'id' => 767,
                'name' => 'umi-wibowo',
                'email' => 'umi-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$dSNBTwYfD8nmqttVd.criuE5X05tfY7PUO01LV.Fkdpm3LIXc/ZKm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            4 => 
            array (
                'id' => 768,
                'name' => 'eko-hutapea',
                'email' => 'eko-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VgVWAoC1QScv6KSB1hgWwe.W3tE8oRcRQztZZ0HofDvfLOnI6Lobe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            5 => 
            array (
                'id' => 769,
                'name' => 'tono-tambunan',
                'email' => 'tono-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$z2erBKPvG8i0PJQhqIdA0OjgOaPn7ybEXxNRkx2MiC/KFfpzuer/y',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:26',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            6 => 
            array (
                'id' => 770,
                'name' => 'agus-sihombing',
                'email' => 'agus-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$rc45ihLAHumBx.KoNxImUe0JnrfPT9gU6OUv.4LfUXGmVF56izXC6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:26',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            7 => 
            array (
                'id' => 771,
                'name' => 'gita-sinaga',
                'email' => 'gita-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.niUq3lfrKONoxXGQ9J0hu7Jlzcq0ZVzGiyjPbYnc5LAnrglghrMu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            8 => 
            array (
                'id' => 772,
                'name' => 'gita-tambunan',
                'email' => 'gita-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$kCvtA/yltj5Vd.cpOyvRGOjUESkPVAYJLI8mbaVIRLMxJyWfdtrsa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            9 => 
            array (
                'id' => 773,
                'name' => 'umi-nasution',
                'email' => 'umi-nasution@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$t77lCeKjlL5AvPshAQrvhO3/Gwfopuy3LQZiRCVON04zEShbu2JLS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            10 => 
            array (
                'id' => 774,
                'name' => 'dewi-tambunan',
                'email' => 'dewi-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$24iT3Osq3n9a6nkxqpxgPuDV08d.9JN2VH7Zx2.z98SSlhsllWhnC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            11 => 
            array (
                'id' => 775,
                'name' => 'slamet-hidayat',
                'email' => 'slamet-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/2vXedsWB4FTYVhgnF8tIO9Gq86RjKeJWScKV1nr3KSXkTLO9nidq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            12 => 
            array (
                'id' => 776,
                'name' => 'kadek-lestari',
                'email' => 'kadek-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$ChPDe2JakTeX0HJHKTfQVOcbaGztTY9Oi3IlnQFC5kAQXD/qWRhpO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            13 => 
            array (
                'id' => 777,
                'name' => 'dewi-rahayu',
                'email' => 'dewi-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lxxIAemYyiLGtcegX1hJj.M1txYNtWc75mLeqXanNLn4UIsBirvGS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            14 => 
            array (
                'id' => 778,
                'name' => 'andi-ramadhan',
                'email' => 'andi-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$dLTovZWVvXmJJL6oAP6dbuvDdAE2db0kjW2DugDQnM7wkSj8Qv6Ty',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            15 => 
            array (
                'id' => 779,
                'name' => 'bambang-saputra',
                'email' => 'bambang-saputra@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fjIk5DsY5vNddslGWI6e.O8cONw2xZQ4qzXt7Hw7eWQC2dmE4TROm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            16 => 
            array (
                'id' => 780,
                'name' => 'fajar-hutapea',
                'email' => 'fajar-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OYqmtHKVLGW4u2GwTlK8XuZS5rqtEEIQAWZC/G2ZxAsHgbzzFvAYK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            17 => 
            array (
                'id' => 781,
                'name' => 'fajar-sihombing',
                'email' => 'fajar-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zw74O2.9AHM70pBaMMtRded0kGOt21rBK0GSPeEJq9w/aYv9X9ymq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            18 => 
            array (
                'id' => 782,
                'name' => 'endah-susanto',
                'email' => 'endah-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$osmkLNJPmf8W5BZkzdRAeOEv42DmIvFFnNCJgafZHBg4V91qD6j22',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            19 => 
            array (
                'id' => 783,
                'name' => 'rina-tambunan',
                'email' => 'rina-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DsOwDfjbRFo8rOWx0j1ToOR/SUblLFXAFCtIcqFANMAk0v/QqyT6a',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:31',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            20 => 
            array (
                'id' => 784,
                'name' => 'wahyu-silitonga',
                'email' => 'wahyu-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$4uTnEtdRAFBik6P8i/M05OR82drEmIknumi/68uKZEt4Mr/mjs.hm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:31',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            21 => 
            array (
                'id' => 785,
                'name' => 'lina-setiawan',
                'email' => 'lina-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w0LlCg.BkL1xsYeUQlaXmeBRGe1MbDJIQmSZXy7ZcJdhASvL/H2BK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:32',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            22 => 
            array (
                'id' => 786,
                'name' => 'gita-anggraini',
                'email' => 'gita-anggraini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$MjfGMSNtewC2yQsAIfGksunvQmRpxozAJjBTBW..zJodZZDz44OI2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            23 => 
            array (
                'id' => 787,
                'name' => 'dewi-pratama',
                'email' => 'dewi-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$8VUo5XkkiJ954WmvoaCGU.HWZBTT/mxMmXtDgolQKL/GT7wGl0v2W',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            24 => 
            array (
                'id' => 788,
                'name' => 'andi-simanjuntak',
                'email' => 'andi-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$nSnaK1hQoFI/MNq88wGYcOvYAHejk1FwRqZqBGPJ6x2VTemu60bqa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            25 => 
            array (
                'id' => 789,
                'name' => 'wahyu-santoso',
                'email' => 'wahyu-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$UfouZG0OlffkcPLS//XYBenIxw6IgMkzwqFWhjXTkPyNgS7syapFq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            26 => 
            array (
                'id' => 790,
                'name' => 'made-anggraini',
                'email' => 'made-anggraini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w8htDHSZN4P5DGhoHVeXU.n1K28QZRU57Qaj2NjfezT.nKiaas36m',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            27 => 
            array (
                'id' => 791,
                'name' => 'sari-maulana',
                'email' => 'sari-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$78VydxhaX/iYv9wrAaJ7JuRJVnTviYcWdjmzDrKu4J4Hnls/Gjnje',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            28 => 
            array (
                'id' => 792,
                'name' => 'slamet-tambunan',
                'email' => 'slamet-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$hDjBKZKMIBh82l7rFfw91uH5cbnrZfY.4qC1AOSik9SOsQbqdd31e',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            29 => 
            array (
                'id' => 793,
                'name' => 'andi-sinaga',
                'email' => 'andi-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SIF0c1KXgs6PSH8lrq8sEOp52AAUEaZ4Avn1rwjlpW1T58hiZjGHm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:35',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            30 => 
            array (
                'id' => 794,
                'name' => 'umi-utami',
                'email' => 'umi-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QBAmJz1MqjFUGNde1063Ye/uH9DRXmwkiawwMzyot71.mRDrYYIvS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:35',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            31 => 
            array (
                'id' => 795,
                'name' => 'slamet-halim',
                'email' => 'slamet-halim@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$pA3Y4RhycRPu1qBYeioE.esgxUUdLZQCgKaSdEqa/klRKYF.cgv5C',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:36',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            32 => 
            array (
                'id' => 796,
                'name' => 'eko-utami',
                'email' => 'eko-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$enXze4mW1zgFFZrsJ.pcO.25QSNT0C2kbZCp5aVkU9xMvG8QmTwJe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:36',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            33 => 
            array (
                'id' => 797,
                'name' => 'cahyo-tambunan',
                'email' => 'cahyo-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$skyl/pIPJ7PyTxd696Y3R.CYdCPpcxUtui3gi8TiW7TDoNdxJTRgC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:37',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            34 => 
            array (
                'id' => 798,
                'name' => 'eko-sihombing',
                'email' => 'eko-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$04OVNh9K.83CNmbbOqBQ4.0G8PtkAlc9abqHX2nXesytU3Tam6o1e',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:37',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            35 => 
            array (
                'id' => 799,
                'name' => 'umi-silitonga',
                'email' => 'umi-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xoI73LTF3Mq19Woic5KLauHGI0Y.67K0Qn7Wa9wUqq33JFIrnXU2.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:38',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            36 => 
            array (
                'id' => 800,
                'name' => 'tono-sihombing',
                'email' => 'tono-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$UVNmIPc3btKlk570GHWF2urRRRlMFi7kx/IovDcDRqv87wAA8.tdK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:38',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            37 => 
            array (
                'id' => 801,
                'name' => 'zainal-nugroho',
                'email' => 'zainal-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$I8JZpDS5fkUwimDiLnXXWuap/AB0bZ0FvQx/X1hq2U1jTBaxPpVgG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            38 => 
            array (
                'id' => 802,
                'name' => 'budi-rahayu',
                'email' => 'budi-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w82r7QXZvx5IEtWA4nm9xO8TWyHQHEZos9zYWgw./D.MdZJF.9/DK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            39 => 
            array (
                'id' => 803,
                'name' => 'dedi-lestari',
                'email' => 'dedi-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$3vSUPOmndoZhJ/SCgZPIkeUG25koQkzYs3l65OPhBKl5hstX/FKmy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            40 => 
            array (
                'id' => 804,
                'name' => 'endah-firmansyah',
                'email' => 'endah-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$tV0SFf664cJVj6ZRDFmahOLX5qNniLRFXPGoP4d7W/5ISx0rpjtNS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            41 => 
            array (
                'id' => 805,
                'name' => 'yanti-hidayat',
                'email' => 'yanti-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/a39I9y/z/gtNsB7/7m33uV0Sz4Y6v6BAVb2v0U986zMjlrdxNnDi',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            42 => 
            array (
                'id' => 806,
                'name' => 'cahyo-siahaan',
                'email' => 'cahyo-siahaan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$aqSj5abwmrwk3NJFRKe7OuArvIACXxHMxi2XIwmqy/quM0bT63rYe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            43 => 
            array (
                'id' => 807,
                'name' => 'kadek-siregar',
                'email' => 'kadek-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$KXrWc1KfCGBGrlJFRK3m.uAKwP6VuW7/FZxY2LbfRwoSWn3eCFdl6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:41',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            44 => 
            array (
                'id' => 808,
                'name' => 'eko-pratama',
                'email' => 'eko-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$jJuAAQatXa/ARGMDpTRmpORkGrNJTduumhcbCsRlfSb5k0WBQRwgu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:41',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            45 => 
            array (
                'id' => 809,
                'name' => 'rina-wibowo',
                'email' => 'rina-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Y2qrMIWUBCBjjVWFZJE2hu2L3xrSDKDWJSkVoRMBZdNuwCIaq5Jg6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            46 => 
            array (
                'id' => 810,
                'name' => 'made-purba',
                'email' => 'made-purba@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$CYyghEFVNDOcwEgYer3T0.ogSYgRo2kfNe1d8Hmd4b//4yRJ85A6S',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            47 => 
            array (
                'id' => 811,
                'name' => 'andi-firmansyah',
                'email' => 'andi-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lyY5Sb0BiavFxV0EiXkReuCFtaWjuOKbYaEp1wXaT0bKCdb..JV8O',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            48 => 
            array (
                'id' => 812,
                'name' => 'endah-rahayu',
                'email' => 'endah-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$utapI1e.7wfDRcxP/Xg6eutXMc8tOy342QVBZIlsSJ5btgqExSJc6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            49 => 
            array (
                'id' => 813,
                'name' => 'nina-nugroho',
                'email' => 'nina-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$3PmXpdjb2xVdtp3TRAV8HenWjq1tLBTOhKpf8a4cry7urgnxtjnn6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            50 => 
            array (
                'id' => 814,
                'name' => 'hadi-halim',
                'email' => 'hadi-halim@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$KmM1JYW3fxQ7wN2TizcBcuU9g1sthabiR7bqbox/TpnJIXDHEomQe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            51 => 
            array (
                'id' => 815,
                'name' => 'joko-tambunan',
                'email' => 'joko-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$eq7H7BjWBUHfoIwjsxv0/u/.2eX9FTgiPBCQnMDjNJ968l0MlY5yq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            52 => 
            array (
                'id' => 816,
                'name' => 'budi-sinaga',
                'email' => 'budi-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$AIwCeN13cBKD62qpGcIgiuGEvKZmWjUKQnWxFOXo6uS1ycfb0gQCu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            53 => 
            array (
                'id' => 817,
                'name' => 'agus-hidayat',
                'email' => 'agus-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2y.BeaeQugKHN37bjFPjwuKCbtoihv.YUSVrR4dUGSPhBJSxGq036',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            54 => 
            array (
                'id' => 818,
                'name' => 'eko-susanto',
                'email' => 'eko-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$W2fSrsEuGgz20QuWfCYE.ubudIGN4znvXgNz3tQyBIZ2.v5E4W17e',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            55 => 
            array (
                'id' => 819,
                'name' => 'bambang-rahayu',
                'email' => 'bambang-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lnEanAAI2.5vhWWQ/zxK2.6nsv6V8Nq0y7xgi.8j2F1lkTx3mGO8S',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:45',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            56 => 
            array (
                'id' => 820,
                'name' => 'adi-purba',
                'email' => 'adi-purba@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ag0jftidkbuaJGgCO/iA/.W144zknh/gAjMcbnpW3Vv0HRktM3AGO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            57 => 
            array (
                'id' => 821,
                'name' => 'ratna-sinaga',
                'email' => 'ratna-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2Yty.T0W4DG7exXUQ6iFJO3/wcw/S6M5.sWc113q1n4NbEuduaA7i',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            58 => 
            array (
                'id' => 822,
                'name' => 'lina-tambunan',
                'email' => 'lina-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$HgMDHS8MYS4yucxtVD8FaO0D5dr2oH2DrL9E/0b77BjhMJiXcNjKy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            59 => 
            array (
                'id' => 823,
                'name' => 'budi-lestari',
                'email' => 'budi-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Yz3dltB0.rEE0Zqo7E60uu4KVDDD2x8e0rg6t524bSFDGCb1/Qf9G',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            60 => 
            array (
                'id' => 824,
                'name' => 'made-setiawan',
                'email' => 'made-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SFVPbSWqNHF03C/oYekW4uATT2IkXuriTQur74nCQGva7KNISkEGe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            61 => 
            array (
                'id' => 825,
                'name' => 'umi-sinaga',
                'email' => 'umi-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QILCUBI6E8BqQHC512.Ufem55gBarxhzd42D3Js2t6UbxeFMSmGy6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            62 => 
            array (
                'id' => 826,
                'name' => 'lina-sinaga',
                'email' => 'lina-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/Feu0jyj2sLBEHFBBU7PL.dbd5fSAYmoGKhwGDdJj2or/JsqxheIu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:48',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            63 => 
            array (
                'id' => 827,
                'name' => 'dwi-simanjuntak',
                'email' => 'dwi-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$hI2Im.Oe9s3GD62KyfGGgu90cNRkYxld.LBwg4WgGrVqhGZw/Pyby',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:48',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            64 => 
            array (
                'id' => 828,
                'name' => 'made-utami',
                'email' => 'made-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$yjONUvOvtt6FGiYtbWFTV.zck9X9cA6ZUzy90mrBz2FbN2Qnm6diO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            65 => 
            array (
                'id' => 829,
                'name' => 'andi-santoso',
                'email' => 'andi-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$3PLoEwt7PshkQK2jO9VCOuDezR.T2KsNEaon.F2g1cfKTAhsxNK12',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            66 => 
            array (
                'id' => 830,
                'name' => 'fajar-wibowo',
                'email' => 'fajar-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$yvYPjXqDs7F6UPy55/g4POp2F2tBOTH3qWymGVLWxGEBx05AXt2f2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            67 => 
            array (
                'id' => 831,
                'name' => 'putra-halim',
                'email' => 'putra-halim@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qltwHqceDk7VI.Fp9tE1UePNBoGvw01jfNQSWjtrrqcarkT.SmqHK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            68 => 
            array (
                'id' => 832,
                'name' => 'zainal-susanto',
                'email' => 'zainal-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$aaQnz9Vo2iB8okFlvJQudO94AiNU/e60Z1KkFvtfKQvRtyjKGq2u.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            69 => 
            array (
                'id' => 833,
                'name' => 'yanti-silitonga',
                'email' => 'yanti-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Gb2hSZzsrQ2TorStdqctBOyeUu197Rw1bHGv6BCupJwf6pEfOZdoC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            70 => 
            array (
                'id' => 834,
                'name' => 'yanti-simanjuntak',
                'email' => 'yanti-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$unZHuSERlGeMyGM76J0VDOgrfKFduuVSqyXPCwEu1IuAbuHxJ0eYy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            71 => 
            array (
                'id' => 835,
                'name' => 'budi-maulana',
                'email' => 'budi-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VAIWcGdleJ5D.X62bIVcR.dow8CEPhTDlF9jiyx1o05POto9XUcYG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            72 => 
            array (
                'id' => 836,
                'name' => 'wahyu-siregar',
                'email' => 'wahyu-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$kmSO.fdm51AORORzNdx5vu6Wor/p.2BOJ8y/pycEPHKiH8PZd7YO2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            73 => 
            array (
                'id' => 837,
                'name' => 'adi-gunawan',
                'email' => 'adi-gunawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$h5sL3Fqi4tsUrdgIH8XFHODQKGuz4AFFhGJX2sGgI5wIqAuBF6tnq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            74 => 
            array (
                'id' => 838,
                'name' => 'bambang-simanjuntak',
                'email' => 'bambang-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$F5EPf1Fy7z01UgmbzYUPQ.ffLLMGVXuWIPKqqxXiboAExrh6OUmy.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            75 => 
            array (
                'id' => 839,
                'name' => 'rina-manullang',
                'email' => 'rina-manullang@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ur2uGAxD5Q/SX9RjeAGWzOLn.qin1td7BclXaN3B5lXqTb/esD1WG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            76 => 
            array (
                'id' => 840,
                'name' => 'slamet-ramadhan',
                'email' => 'slamet-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$EYv1somPIYbFVThaxBec8.hRjZ28z5S/dIeFBVZ1XgY.6/NlQCXG6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            77 => 
            array (
                'id' => 841,
                'name' => 'budi-hidayat',
                'email' => 'budi-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lDY5DYrRYJzqz/k05.oeNue6ks8XUBbZ9/Y/VwPI7ixC.LDXvMfGu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            78 => 
            array (
                'id' => 842,
                'name' => 'gita-sihombing',
                'email' => 'gita-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zHNfSxhW/RjqlwvPknvI7ON584h3ZeXTgnrPjnsJi10Bsv2qcSqNu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            79 => 
            array (
                'id' => 843,
                'name' => 'joko-nugroho',
                'email' => 'joko-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$f.vCpdaPNleWgzB6GOUW4uqYkkcokqpN1dN2V04sq7qtJNJMj/bh2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            80 => 
            array (
                'id' => 844,
                'name' => 'eko-wijaya',
                'email' => 'eko-wijaya@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qTzbTrzyHif1Edr5nk8IH.N12TYYNdL0jzlFReUViptD6DPD5Wjoa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            81 => 
            array (
                'id' => 845,
                'name' => 'umi-hutapea',
                'email' => 'umi-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$mdztALDZqNpKCogmm58.iemx0ZaEG74MvUgRCJKjTUjiM/X885kjG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:54',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            82 => 
            array (
                'id' => 846,
                'name' => 'agus-santoso',
                'email' => 'agus-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$YIgv8dSJ3NPEG7L2SihyDuEg2r3PB2ONpwwG.svM6wWN5Vg4Q9DFe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:54',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            83 => 
            array (
                'id' => 847,
                'name' => 'rudi-hartono',
                'email' => 'rudi-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            84 => 
            array (
                'id' => 848,
                'name' => 'susi-susanti',
                'email' => 'susi-susanti@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            85 => 
            array (
                'id' => 849,
                'name' => 'teguh-prasetyo',
                'email' => 'teguh-prasetyo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            86 => 
            array (
                'id' => 850,
                'name' => 'dian-pertiwi',
                'email' => 'dian-pertiwi@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            87 => 
            array (
                'id' => 851,
                'name' => 'hendra-gunawan',
                'email' => 'hendra-gunawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            88 => 
            array (
                'id' => 852,
                'name' => 'ratih-kumala',
                'email' => 'ratih-kumala@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            89 => 
            array (
                'id' => 853,
                'name' => 'rina-marlina',
                'email' => 'rina-marlina@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            90 => 
            array (
                'id' => 854,
                'name' => 'bowo-laksono',
                'email' => 'bowo-laksono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            91 => 
            array (
                'id' => 855,
                'name' => 'sri-wahyuni',
                'email' => 'sri-wahyuni@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            92 => 
            array (
                'id' => 856,
                'name' => 'bambang-tambunan',
                'email' => 'bambang-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$NmOjE3rSW1EwHf3YRJiC1Oi7aFqDTVN/.nRDZWBZ.ACA1JXcO4pZS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:45',
                'updated_at' => '2026-09-07 14:12:45',
            ),
            93 => 
            array (
                'id' => 857,
                'name' => 'dewi-nasution',
                'email' => 'dewi-nasution@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$45Bf6WsRU98OJnqZPsGA1uLxmxmF6.UfRagKzLZ7LB8JCQS3UvVI2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:45',
                'updated_at' => '2026-09-07 14:12:45',
            ),
            94 => 
            array (
                'id' => 858,
                'name' => 'tono-maulana',
                'email' => 'tono-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$AfOICV5Fl6ksBhrSxPfTsu/rZPcD0h/djTuhB/U3YubvUWaqaiaQq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:46',
                'updated_at' => '2026-09-07 14:12:46',
            ),
            95 => 
            array (
                'id' => 859,
                'name' => 'eko-siregar',
                'email' => 'eko-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$aKw.MO5Bdn6GbjYFz/4KwO.PRzhAqvB/0NFZc.TyxbRTxYnnHLTMa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:46',
                'updated_at' => '2026-09-07 14:12:46',
            ),
            96 => 
            array (
                'id' => 860,
                'name' => 'slamet-hutapea',
                'email' => 'slamet-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qTVSEtVv60KpZ66FV9HdNuhVk7LFfK5huCySgD6H5Fd57CqUDBpuW',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:46',
                'updated_at' => '2026-09-07 14:12:46',
            ),
            97 => 
            array (
                'id' => 861,
                'name' => 'putra-manullang',
                'email' => 'putra-manullang@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$8L0RFYFGyaeMDFFtdTpGqO06FoX1gUu/H6Y/l1uRqZbpqu/EZ6nl.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:47',
                'updated_at' => '2026-09-07 14:12:47',
            ),
            98 => 
            array (
                'id' => 862,
                'name' => 'indah-maulana',
                'email' => 'indah-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$e9Z5/G.TB/VVOB5R7u8b7uR9E6EGD1MEnMTxuhu1jbX1JUx0f1PZ.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:47',
                'updated_at' => '2026-09-07 14:12:47',
            ),
            99 => 
            array (
                'id' => 863,
                'name' => 'wahyu-wibowo',
                'email' => 'wahyu-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$M0fiT6om8MetkVu/mkoe4eJJDx7ZnRmSvIQrEQdPvD3/miiBbY3Ii',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:47',
                'updated_at' => '2026-09-07 14:12:47',
            ),
            100 => 
            array (
                'id' => 864,
                'name' => 'slamet-kusuma',
                'email' => 'slamet-kusuma@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$WO2sZ8tzzHoJUiA54FMW1.Tdxe2YV5CAx5zlSCZv4fPHJrh5dX/Q.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:48',
                'updated_at' => '2026-09-07 14:12:48',
            ),
            101 => 
            array (
                'id' => 865,
                'name' => 'joko-saputra',
                'email' => 'joko-saputra@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$vNcqAWs9iKccF9rDDwQGBOV9Aa8odPONPoHaecT.2HhFhTE4m4ZoC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:48',
                'updated_at' => '2026-09-07 14:12:48',
            ),
            102 => 
            array (
                'id' => 866,
                'name' => 'eko-simanjuntak',
                'email' => 'eko-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L4.Z/G.gOgyUTF0.RWfR0OhgmEmM8oSMWnm.l29D5M3vvHEnbkt0W',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:48',
                'updated_at' => '2026-09-07 14:12:48',
            ),
            103 => 
            array (
                'id' => 867,
                'name' => 'tono-saputra',
                'email' => 'tono-saputra@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$MYuV/w8.cnfLxU3nYmvZcuUMjjrfQh.xfPZ.r3crYTjHv18nqWISS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:49',
                'updated_at' => '2026-09-07 14:12:49',
            ),
            104 => 
            array (
                'id' => 868,
                'name' => 'lina-simanjuntak',
                'email' => 'lina-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$h6/fUEpBYwgNqwLVuI/ZxOaarrPwAOTL9w8oV5K37fQJNhn7WSsui',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:49',
                'updated_at' => '2026-09-07 14:12:49',
            ),
            105 => 
            array (
                'id' => 869,
                'name' => 'dwi-utami',
                'email' => 'dwi-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$eBOK9GEh1O7BG.J1UNyjU.zaNeQZLoEI7nt1vMBbjRhOS7KkLKVYK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:50',
                'updated_at' => '2026-09-07 14:12:50',
            ),
            106 => 
            array (
                'id' => 870,
                'name' => 'endah-pratama',
                'email' => 'endah-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QcrsxzRbhRpYnY0U7BDAKuIQcM7XirXdAYgH8En2a3GOUqSHbxQby',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:50',
                'updated_at' => '2026-09-07 14:12:50',
            ),
            107 => 
            array (
                'id' => 871,
                'name' => 'nina-silitonga',
                'email' => 'nina-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$nZRWawftzSbXXw/hOcBvmOBZ7kmqFlxWkkRQazzexhAJZN57nK/EW',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:12:50',
                'updated_at' => '2026-09-07 14:12:50',
            ),
            108 => 
            array (
                'id' => 899,
                'name' => 'hadi-lestari',
                'email' => 'hadi-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$D1oRwoYC9c2.jS9AeeBLWuoZwAIBxKbq526UZvJoo66ksMvnKFjC.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:40',
                'updated_at' => '2026-09-07 14:17:40',
            ),
            109 => 
            array (
                'id' => 900,
                'name' => 'bambang-lestari',
                'email' => 'bambang-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$NQBKQOKxl7Scr6Z25C2yAOznaHZhGkRBYB.X7sUtN4W/cwZIwZehy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:40',
                'updated_at' => '2026-09-07 14:17:40',
            ),
            110 => 
            array (
                'id' => 901,
                'name' => 'eko-hidayat',
                'email' => 'eko-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Du7YhVRy.9r34gIPhtDbIuqqmaerl8DMY0R1gNyo9wcrycUjcOGfi',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:41',
                'updated_at' => '2026-09-07 14:17:41',
            ),
            111 => 
            array (
                'id' => 902,
                'name' => 'endah-ramadhan',
                'email' => 'endah-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VKZFkFNsJKIpeVKhJFSXTeLEi6DvYN3sFXlWK08YPP0Yo1ppMXUYm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:41',
                'updated_at' => '2026-09-07 14:17:41',
            ),
            112 => 
            array (
                'id' => 903,
                'name' => 'budi-tambunan',
                'email' => 'budi-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$gwznSFiSkSLd8PxLBzbEWOYGwx2ZHJoZZlydL4lShlAaciRO.RlE.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:41',
                'updated_at' => '2026-09-07 14:17:41',
            ),
            113 => 
            array (
                'id' => 904,
                'name' => 'indah-santoso',
                'email' => 'indah-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DWJkJW93r47dw5jsRWGFVOsq8zcbcFAhCq1sv.kv7rCobKkswKhXS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:42',
                'updated_at' => '2026-09-07 14:17:42',
            ),
            114 => 
            array (
                'id' => 905,
                'name' => 'indah-tambunan',
                'email' => 'indah-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$x7YYdKz14Rm65P5uD4OsDuc9an8/UeFBeZyDYc/UDt4gGDkKEvbKm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:42',
                'updated_at' => '2026-09-07 14:17:42',
            ),
            115 => 
            array (
                'id' => 906,
                'name' => 'joko-siregar',
                'email' => 'joko-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lnden5CKMXpfKnC0Zm2YXeq4hCpbw1BI0hMyNJOKvpEjC7QOwtCb6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:42',
                'updated_at' => '2026-09-07 14:17:42',
            ),
            116 => 
            array (
                'id' => 907,
                'name' => 'adi-setiawan',
                'email' => 'adi-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$bIy.jaYbMxHfBdmuUa4PpOgBSml3DsrAxgpkhzn/w9gNdVpBJ0lyK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:42',
                'updated_at' => '2026-09-07 14:17:42',
            ),
            117 => 
            array (
                'id' => 908,
                'name' => 'ratna-simanjuntak',
                'email' => 'ratna-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DWWuix2/fYYe3itplmkhZOqrq8PR2uLFcrKOCNGAP1BtVylJIgDoO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:43',
                'updated_at' => '2026-09-07 14:17:43',
            ),
            118 => 
            array (
                'id' => 909,
                'name' => 'tono-wibowo',
                'email' => 'tono-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DDg6KnNVa8DlzyAPRm1OweyyZFQHekg4uC31cJ65VHJ0FmHhR22lq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:43',
                'updated_at' => '2026-09-07 14:17:43',
            ),
            119 => 
            array (
                'id' => 910,
                'name' => 'putra-anggraini',
                'email' => 'putra-anggraini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$82p4m4BHRx/Az44jHuPFz..06bXdne/LV0hCfdKRy7jDuTB9tjLQq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:43',
                'updated_at' => '2026-09-07 14:17:43',
            ),
            120 => 
            array (
                'id' => 911,
                'name' => 'dwi-ramadhan',
                'email' => 'dwi-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ndyf7vHKMg8FLlHxSQA5Neb4VLzt6vsdXOENSCP8htAhAq29CIVSO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:44',
                'updated_at' => '2026-09-07 14:17:44',
            ),
            121 => 
            array (
                'id' => 912,
                'name' => 'adi-hutapea',
                'email' => 'adi-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Q55aJsyxDFfGkgYJgkztOu4eDqv.lpmHXKzLqWscTmOKloP4crFp6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:44',
                'updated_at' => '2026-09-07 14:17:44',
            ),
            122 => 
            array (
                'id' => 913,
                'name' => 'kadek-nugroho',
                'email' => 'kadek-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$wphBSSN6qzt2LP7D5eIIcezCEMIKCZa4Iyd33sAEjhgpxEgpJ1Fgy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:44',
                'updated_at' => '2026-09-07 14:17:44',
            ),
            123 => 
            array (
                'id' => 914,
                'name' => 'lina-utami',
                'email' => 'lina-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$8am7jEbU47PX0qqgvDVbCem0hBrS7vWShl2cqa.eoL0D4.r4XQFHW',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:44',
                'updated_at' => '2026-09-07 14:17:44',
            ),
            124 => 
            array (
                'id' => 915,
                'name' => 'tono-firmansyah',
                'email' => 'tono-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$RvOlJUG5ks.zSxnP05L72eefL5szDiOQUcJp/9Ro1QuNn132x8Fk2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:45',
                'updated_at' => '2026-09-07 14:17:45',
            ),
            125 => 
            array (
                'id' => 916,
                'name' => 'agus-susanto',
                'email' => 'agus-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$vzwJacgNbVCNtlpZLxccUOkfrEkVCS8mG3HF3HaQN/F3EMMkR2bsu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:45',
                'updated_at' => '2026-09-07 14:17:45',
            ),
            126 => 
            array (
                'id' => 917,
                'name' => 'wahyu-sihombing',
                'email' => 'wahyu-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$F0.Cqb8SkpzDQcmWz27EqeNe2B92pN4ex0Y91CAWqU44sBiiTSbZC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:45',
                'updated_at' => '2026-09-07 14:17:45',
            ),
            127 => 
            array (
                'id' => 918,
                'name' => 'zainal-wibowo',
                'email' => 'zainal-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$q9NIy.hAA5ygCGfa51Yru.f4XwPtFAguXzJC8ZUNppUTbW/Ki.7Ma',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:46',
                'updated_at' => '2026-09-07 14:17:46',
            ),
            128 => 
            array (
                'id' => 919,
                'name' => 'nina-siahaan',
                'email' => 'nina-siahaan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$swMBWO2XAGXA8o3j/rJNI.n7hgZtXUKONO5KHR/vuBDtI.m4qxXxW',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:46',
                'updated_at' => '2026-09-07 14:17:46',
            ),
            129 => 
            array (
                'id' => 920,
                'name' => 'rina-setiawan',
                'email' => 'rina-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OBiDrqzvk9YM2KmIAyujcutGHmlZwlSATpY.2B.SCd0.8f7cdtBte',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:46',
                'updated_at' => '2026-09-07 14:17:46',
            ),
            130 => 
            array (
                'id' => 921,
                'name' => 'joko-sihombing',
                'email' => 'joko-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SJ/xDdzMDNa5DpeUAMw5veH6lKayheGHgdNDKbmhiGBrT5ZvWAC46',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:47',
                'updated_at' => '2026-09-07 14:17:47',
            ),
            131 => 
            array (
                'id' => 922,
                'name' => 'budi-wijaya',
                'email' => 'budi-wijaya@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$vGFmfgqgsuiiWuxcM.3H6.Z/hcOxlpvUMaP2JfVOc3MKx2otLPBLy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 14:17:47',
                'updated_at' => '2026-09-07 14:17:47',
            ),
        ));
        
        
    }
}